### ISSUE TITLE
Sound is distorted as soon as I start BuckleSpring

### ISSUE THREAD

**Issue by cyates559** [zevv/bucklespring#51] opened 2017-06-14 14:40 UTC
I installed bucklespring on my Ubuntu 16.04 desktop using `sudo snap install bucklespring` and then I started bucklespring using `bucklespring.buckle`

Whenever I played sound while this program was running it was distorted and almost sounds like a screeching buckling sound.  I experienced this distortion in Totem Video Player and Google Play Music.
Also, the buckling sound appears to lag by just enough that it is uncomfortable to type.

```
sudo snap install bucklespring
2017-06-14T07:29:44-07:00 INFO snap "core" has bad plugs or slots: core-support-plug (unknown interface)
bucklespring 1.4.0+git-snap2 from '3v1n0' installed
carsen@Sol:~$ bucklespring.buckle 
ssfsdfsdfError opening audio file "/snap/bucklespring/23/wav/72-1.wav": Failed to open file
Error opening audio file "/snap/bucklespring/23/wav/72-0.wav": Failed to open file
Error opening audio file "/snap/bucklespring/23/wav/73-1.wav": Failed to open file
Error opening audio file "/snap/bucklespring/23/wav/73-0.wav": Failed to open file
^C
```
UPDATE:
I opened bucklespring a second time and was experiencing none of these issues. Including the `Error opening audio file`
before running the program a second time, the sound that is supposed to be played on keypress seemed to be either distorted or playing twice on top of itself (if that makes any sense)

**Comment by zevv** [comment] 2017-06-15 11:49
The 'Error opening audio' messages are probably not related, these happen when you hit keys on the keyboard which have no sound file because these keys were not on the original Model-M keyboard. (windows/menu keys for example)

Not sure where your distortion is coming from, likely to be something with your configuration. Unfortunately sound setup on Linux is still hell in 2017. We have Alsa, OSS, Pulseaudio, Jack, OpenAL, and even more then that - the problem can be in any of these drivers or library layers.

You mentioned you hear similar distortion in Totem or Google Play Music, so the issue is not likely to originate in Buckle itself.

**Comment by Fatburger3** [comment] 2017-06-16 06:12
I think you misunderstood me. I ran the program, then every time my computer played audio I heard distorted bucklingspring noises.  When I stopped the program, this excess noise stopped.  Google Play Music and Totem were just two examples...Another example is The volume changing sound that is played by my desktop environment.

**Comment by zevv** [comment] 2017-06-16 18:20
I'm afraid I'm not able to help you out, since the problem is not in the Bucklespring code, but somewhere in your sound setup. 

You're probably best off asking support from the OpenAL people at https://github.com/kcat/openal-soft.

**Comment by zevv** [comment] 2021-11-22 08:18
Closing this one: feel free to re-open if this issue still hits you.

**Closed by zevv** 2021-11-22 08:18 UTC
